apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim # name of the Persistent Volume Claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 3Gi # request 3 Gigabytes of storage
  storageClassName: default # when you use KOPS on AWS, the default storage class uses EBS volumes
