apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprormq-deployment
  labels:
    app: vprormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      labels:
        app: vprormq
    spec:
      containers:
      - name: vprormq
        image: rabbitmq
        ports:
        - name: vprormq-port
          containerPort: 5672 # RabbitMQ default port in 
        env:
        - name: RABBITMQ_DEFAULT_USER # default username fromthe Docker compose file
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS # default password from the Docker compose file
          valueFrom:
            secretKeyRef:
              name: app-secret # referring to the secret created in secret.yaml
              key: rmq-pass # key in the secret that has the password value
